apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: tools
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tools
    app.kubernetes.io/part-of: tools
  name: tools
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: tools
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: tools
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-o11y-tenant/tools/tools@sha256:61a32dbb055dd61ddc8fdcf5621531b5b83c688422a9ab06b73f81fcc97652bf
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
