apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: tools
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tools
    app.kubernetes.io/part-of: tools
  name: tools
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: tools
status:
  loadBalancer: {}
