apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: tools
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-o11y-tenant/tools/tools@sha256:d671861860bcd5e245786efc9c4e1e16c17bd63efbeee39fd3a2b674b2d6cf05
        name: container-image
        resources: {}
status: {}
