apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: tools
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-o11y-tenant/tools/tools@sha256:43cb95ff9a54fba999ec3df9f6ca8aef53302623f248d898117008d1a5e21308
        name: container-image
        resources: {}
status: {}
