apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: tools
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tools
    app.kubernetes.io/part-of: tools
  name: toolsfa5b
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: tools
    weight: 100
status: {}
